// Command envstubgen generates a conservative no-op implementation of a
// wasm2go EnvImports interface. It is used for optional native libraries that
// are linked into pgrust but are not reached by the single-user test path.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	in := flag.String("in", "", "generated base.go")
	out := flag.String("out", "", "output Go file")
	pkg := flag.String("package", "host", "output package")
	baseImport := flag.String("base-import", "", "generated base package import")
	flag.Parse()
	if *in == "" || *out == "" || *baseImport == "" {
		fmt.Fprintln(os.Stderr, "-in, -out and -base-import are required")
		os.Exit(2)
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, *in, nil, 0)
	check(err)
	var iface *ast.InterfaceType
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if ok && typeSpec.Name.Name == "EnvImports" {
				iface, _ = typeSpec.Type.(*ast.InterfaceType)
			}
		}
	}
	if iface == nil {
		check(fmt.Errorf("EnvImports not found in %s", *in))
	}

	var body bytes.Buffer
	fmt.Fprintf(&body, "// Code generated by envstubgen; DO NOT EDIT.\npackage %s\n\nimport base %q\n\n", *pkg, *baseImport)
	body.WriteString("// Env supplies inert fallbacks for optional SSL, ICU, and XML imports.\ntype Env struct{}\n\n")
	for _, field := range iface.Methods.List {
		if len(field.Names) != 1 {
			continue
		}
		var signature bytes.Buffer
		check(format.Node(&signature, fset, field.Type))
		sig := strings.ReplaceAll(signature.String(), "*Module", "*base.Module")
		fn, ok := field.Type.(*ast.FuncType)
		if !ok {
			continue
		}
		fmt.Fprintf(&body, "func (Env) %s%s {", field.Names[0].Name, strings.TrimPrefix(sig, "func"))
		if fn.Results != nil && len(fn.Results.List) != 0 {
			body.WriteString(" return 0 ")
		}
		body.WriteString("}\n")
	}

	formatted, err := format.Source(body.Bytes())
	check(err)
	check(os.WriteFile(*out, formatted, 0o644))
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
